apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoicebot-app
  namespace: default
  labels:
    app: invoicebot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: invoicebot
  template:
    metadata:
      labels:
        app: invoicebot
    spec:
      containers:
      - name: invoicebot
        image: invoicebot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: invoicebot-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: invoicebot-secrets
              key: DB_PASSWORD
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: invoicebot-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: invoicebot-secrets
              key: AWS_SECRET_ACCESS_KEY
        envFrom:
        - configMapRef:
            name: invoicebot-config
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
