# External Secrets Operator Configuration
# This uses AWS Secrets Manager to inject secrets into Kubernetes

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        secretRef:
          accessKeyID:
            name: aws-credentials
            key: access-key-id
          secretAccessKey:
            name: aws-credentials
            key: secret-access-key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: invoicebot-external-secret
  namespace: default
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: invoicebot-secrets
    creationPolicy: Owner
  data:
  - secretKey: DB_USER
    remoteRef:
      key: invoicebot/database
      property: username
  - secretKey: DB_PASSWORD
    remoteRef:
      key: invoicebot/database
      property: password
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: invoicebot/aws
      property: access_key_id
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: invoicebot/aws
      property: secret_access_key
